import { columns } from "@/components/Booking/Revenue/revenue-columns";
import { DataTable } from "@/components/Booking/Revenue/revenue-table";

import { Revenue } from "@/actions/data";

async function getData(): Promise<Revenue[]> {
  // Fetch data from your API here.
  return [
    {
      id: "rev-001",
      date: "2024-07-18",
      category: "Sales",
      source: "Website Sale",
      amount: 125.5,
      note: "Order #1050",
    },
    {
      id: "rev-002",
      date: "2025-01-20",
      category: "Subscription",
      source: "Monthly Software Fee",
      amount: 49.0,
      note: "User account renewal",
    },
    {
      id: "rev-003",
      date: "2023-11-05",
      category: "Service",
      source: "Consulting Fee",
      amount: 850.0,
      note: "Project alpha phase 1",
    },
    {
      id: "rev-004",
      date: "2024-04-11",
      category: "Usage-Based",
      source: "Cloud Hosting Bill",
      amount: 78.2,
      note: "", // Note is an empty string
    },
    {
      id: "rev-005",
      date: "2025-05-01",
      category: "Interest",
      source: "Savings Account Interest",
      amount: 5.3,
      note: "April 2025 interest payout",
    },
    {
      id: "rev-006",
      date: "2024-09-03",
      category: "Sales",
      source: "In-Store Purchase",
      amount: 310.75,
      note: "Receipt #4501",
    },
    {
      id: "rev-007",
      date: "2025-02-14",
      category: "Licensing",
      source: "Software License Renewal",
      amount: 1200.0,
      note: "Annual license for client X",
    },
    {
      id: "rev-008",
      date: "2023-10-29",
      category: "Service",
      source: "Maintenance Contract",
      amount: 350.0,
      note: "", // Note is an empty string
    },
    {
      id: "rev-009",
      date: "2024-12-19",
      category: "Subscription",
      source: "Annual Membership Fee",
      amount: 299.0,
      note: "Membership renewal",
    },
    {
      id: "rev-010",
      date: "2025-03-08",
      category: "Rent",
      source: "Office Space Rental",
      amount: 1500.0,
      note: "March rent payment",
    },
    {
      id: "rev-011",
      date: "2024-01-25",
      category: "Sales",
      source: "E-commerce Sale",
      amount: 88.99,
      note: null, // Still showing some null just in case, but schema implies string
    },
    {
      id: "rev-012",
      date: "2025-04-02",
      category: "Service",
      source: "Installation Fee",
      amount: 400.0,
      note: "New client setup",
    },
    {
      id: "rev-013",
      date: "2023-07-10",
      category: "Sales",
      source: "Website Sale",
      amount: 55.0,
      note: "Small item purchase",
    },
    {
      id: "rev-014",
      date: "2024-08-30",
      category: "Usage-Based",
      source: "API Usage Fees",
      amount: 115.6,
      note: "",
    },
    {
      id: "rev-015",
      date: "2025-06-16",
      category: "Subscription",
      source: "Quarterly Service Fee",
      amount: 150.0,
      note: "Q2 service subscription",
    },
    {
      id: "rev-016",
      date: "2024-02-01",
      category: "Interest",
      source: "Investment Dividend",
      amount: 25.75,
      note: "Quarterly dividend",
    },
    {
      id: "rev-017",
      date: "2023-09-12",
      category: "Service",
      source: "Repair Service",
      amount: 220.0,
      note: "Equipment repair",
    },
    {
      id: "rev-018",
      date: "2024-10-22",
      category: "Sales",
      source: "In-Store Purchase",
      amount: 45.9,
      note: "",
    },
    {
      id: "rev-019",
      date: "2025-07-07",
      category: "Licensing",
      source: "Content License",
      amount: 750.0,
      note: "Use of stock footage",
    },
    {
      id: "rev-020",
      date: "2024-03-15",
      category: "Subscription",
      source: "Monthly Membership",
      amount: 19.99,
      note: "",
    },
    {
      id: "rev-021",
      date: "2023-08-01",
      category: "Rent",
      source: "Equipment Rental",
      amount: 300.0,
      note: "Monthly equipment lease",
    },
    {
      id: "rev-022",
      date: "2024-11-28",
      category: "Sales",
      source: "Website Sale",
      amount: 65.4,
      note: "Black Friday deal",
    },
    {
      id: "rev-023",
      date: "2025-08-10",
      category: "Service",
      source: "Consulting Fee",
      amount: 1100.0,
      note: "Follow-up consultation",
    },
    {
      id: "rev-024",
      date: "2024-05-09",
      category: "Usage-Based",
      source: "Utility Charges",
      amount: 185.5,
      note: "Electricity usage",
    },
    {
      id: "rev-025",
      date: "2023-12-06",
      category: "Sales",
      source: "E-commerce Sale",
      amount: 250.0,
      note: "Holiday gift purchase",
    },
    {
      id: "rev-026",
      date: "2025-09-21",
      category: "Subscription",
      source: "Annual Service Plan",
      amount: 500.0,
      note: "Premier plan renewal",
    },
    {
      id: "rev-027",
      date: "2024-06-07",
      category: "Interest",
      source: "Business Account Interest",
      amount: 8.15,
      note: "",
    },
    {
      id: "rev-028",
      date: "2023-06-18",
      category: "Service",
      source: "Project Management",
      amount: 900.0,
      note: "Phase 2 completion payment",
    },
    {
      id: "rev-029",
      date: "2024-01-04",
      category: "Sales",
      source: "In-Store Purchase",
      amount: 35.0,
      note: "",
    },
    {
      id: "rev-030",
      date: "2025-10-05",
      category: "Licensing",
      source: "Patent License",
      amount: 3000.0,
      note: "Quarterly patent usage fee",
    },
    {
      id: "rev-031",
      date: "2024-02-29", // Leap year date
      category: "Subscription",
      source: "Monthly Access Fee",
      amount: 25.0,
      note: "",
    },
    {
      id: "rev-032",
      date: "2023-05-22",
      category: "Sales",
      source: "Website Sale",
      amount: 175.8,
      note: "Repeat customer order",
    },
    {
      id: "rev-033",
      date: "2025-11-11",
      category: "Service",
      source: "Training Workshop",
      amount: 600.0,
      note: "Corporate training session",
    },
    {
      id: "rev-034",
      date: "2024-07-01",
      category: "Rent",
      source: "Vehicle Lease",
      amount: 450.0,
      note: "Monthly lease payment",
    },
    {
      id: "rev-035",
      date: "2023-04-15",
      category: "Usage-Based",
      source: "Data Transfer Fees",
      amount: 95.1,
      note: "",
    },
    {
      id: "rev-036",
      date: "2025-12-03",
      category: "Sales",
      source: "E-commerce Sale",
      amount: 550.0,
      note: "High-value item",
    },
    {
      id: "rev-037",
      date: "2024-08-19",
      category: "Subscription",
      source: "Magazine Subscription",
      amount: 30.0,
      note: "Annual print subscription",
    },
    {
      id: "rev-038",
      date: "2023-03-10",
      category: "Service",
      source: "Consulting Fee",
      amount: 700.0,
      note: "",
    },
    {
      id: "rev-039",
      date: "2025-01-01",
      category: "Interest",
      source: "Annual Bond Interest",
      amount: 150.0,
      note: "Yearly interest payout",
    },
    {
      id: "rev-040",
      date: "2024-09-17",
      category: "Sales",
      source: "In-Store Purchase",
      amount: 110.25,
      note: null,
    },
    {
      id: "rev-041",
      date: "2023-02-08",
      category: "Licensing",
      source: "Music License",
      amount: 400.0,
      note: "Background music usage",
    },
    {
      id: "rev-042",
      date: "2025-02-07",
      category: "Service",
      source: "Website Development",
      amount: 2500.0,
      note: "Website project payment",
    },
    {
      id: "rev-043",
      date: "2024-03-29",
      category: "Usage-Based",
      source: "Storage Fees",
      amount: 40.0,
      note: "",
    },
    {
      id: "rev-044",
      date: "2023-01-16",
      category: "Sales",
      source: "E-commerce Sale",
      amount: 99.5,
      note: "First order of the year",
    },
    {
      id: "rev-045",
      date: "2025-03-31",
      category: "Subscription",
      source: "Premium Service Tier",
      amount: 75.0,
      note: "Tier upgrade",
    },
    {
      id: "rev-046",
      date: "2024-10-10",
      category: "Rent",
      source: "Equipment Rental",
      amount: 320.0,
      note: "Additional equipment rental",
    },
    {
      id: "rev-047",
      date: "2023-04-04",
      category: "Service",
      source: "Legal Consultation",
      amount: 300.0,
      note: "",
    },
    {
      id: "rev-048",
      date: "2025-04-25",
      category: "Sales",
      source: "Website Sale",
      amount: 140.0,
      note: null,
    },
    {
      id: "rev-049",
      date: "2024-11-15",
      category: "Interest",
      source: "Fixed Deposit Interest",
      amount: 80.0,
      note: "Semi-annual interest",
    },
    {
      id: "rev-050",
      date: "2023-01-31",
      category: "Subscription",
      source: "Monthly Software Fee",
      amount: 49.0,
      note: "New subscriber",
    },
  ];
}

export default async function RevenuePage() {
  const data = await getData();

  return (
    <main className="flex flex-1 flex-col gap-4 p-4 pt-0">
      <DataTable columns={columns} data={data} />
    </main>
  );
}
